FROM nginx:1.13.12

MAINTAINER showx<9448923@qq.com>

# RUN apt-get update

VOLUME /webwww/nginx/conf /etc/nginx/conf
VOLUME /webwww/www/ /webwww/www/
VOLUME /webwww/log/nginx /webwww/log/nginx

EXPOSE 80